export const btnItems = [
    {
        title: "게임",
        reward: "수박게임 · 2048 ",
        to: "/",
        key: "Untitled5",
    },
    {
        title: "계좌 계설",
        reward: "토스뱅크 · 타 은행/증권",
        to: "/",
        key: "Untitled6",
    },
    {
        title: "교통",
        reward: "자전거 대여 · 택시 · 기차 예야 ",
        to: "/",
        key: "Untitled9",
    },
    {
        title: "내 보험",
        reward: "병원비 청구 · 상담 · 상품 ",
        to: "/",
        key: "Untitled10",
    },
    {
        title: "내 자동차",
        reward: "내 차 관리 · 차 구매 · 혜택 ",
        to: "/",
        key: "Untitled11",
    },
    {
        title: "내 자산",
        reward: "계좌 · 대출 · 증권 · 포인트 · 분석 ",
        to: "/",
        key: "Untitled12",
    },
    {
        title: "내 카드",
        reward: "카드 발급 · 혜택추천 · 이벤트 ",
        to: "/",
        key: "Untitled13",
    },
    {
        title: "대출 받기",
        reward: "신용 · 주택 · 대환 · 내 대출 ",
        to: "/",
        key: "Untitled14",
    },
    {
        title: "머니라운지",
        reward: "커뮤니티티 ",
        to: "/",
        key: "Untitled42",
    },
    {
        title: "멤버십 포인트",
        reward: "멤버십 조회 · 적립 ",
        to: "/",
        key: "Untitled15",
    },
    {
        title: "모바일 · 인터넷",
        reward: "통신요금 · 기기구매 ",
        to: "/",
        key: "Untitled16",
    },
    {
        title: "미니앱",
        reward: "설치없이 쓸 수 있는 앱 156개 ",
        to: "/",
        key: "Untitled17",
    },
    {
        title: "민원",
        reward: "증명서 · 공공알림",
        to: "/",
        key: "Untitled19",
    },
    {
        title: "부동산",
        reward: "주택담보대출 · 내 집 사기 · 청약 ",
        to: "/",
        key: "Untitled18",
    },
    {
        title: "브랜드콘",
        reward: "구매 · 선물하기",
        to: "/",
        key: "Untitled20",
    },
    {
        title: "사장님 · 광고",
        reward: "매출 장부 · 사장님대출 · 광고문의",
        to: "/",
        key: "Untitled21",
    },
    {
        title: "세금",
        reward: "국/지방세 · 환급",
        to: "/",
        key: "Untitled22",
    },
    {
        title: "소비",
        reward: "내역 · 카드값 · 분석",
        to: "/",
        key: "Untitled23",
    },
    {
        title: "송금",
        reward: "자동이체 · 더치페이",
        to: "/",
        key: "Untitled24",
    },
    {
        title: "쇼핑",
        reward: "토스쇼핑 · 가격비교",
        to: "/",
        key: "Untitled25",
    },
    {
        title: "신용점수",
        reward: "점수 올리기 · 내역",
        to: "/",
        key: "Untitled26",
    },
    {
        title: "연금 준비",
        reward: "토스뱅크 제휴 연금",
        to: "/",
        key: "Untitled12",
    },
    {
        title: "자녀",
        reward: "어린이 · 청소년 서비스",
        to: "/",
        key: "Untitled27",
    },
    {
        title: "토스뱅크 상품",
        reward: "계좌 · 대출 · 카드",
        to: "/",
        key: "Untitled28",
    },
    {
        title: "토스페이",
        reward: "온라인 · 오프라인 결제",
        to: "/",
        key: "Untitled29",
    },
    {
        title: "토스프라임 멤버십",
        reward: "최대 4%캐시백",
        to: "/",
        key: "Untitled30",
    },
    {
        title: "투자",
        reward: "토스증권 · 채권 · 조각투자",
        to: "/",
        key: "Untitled31",
    },
    {
        title: "편의점 택배",
        reward: "CU · GS25",
        to: "/",
        key: "Untitled32",
    },
    {
        title: "해외여행",
        reward: "환전 · 결제 · 보험 · 스마트패스",
        to: "/",
        key: "Untitled33",
    },
    {
        title: "혜택",
        reward: "만보기 · 행운복권 · 라이브쇼핑",
        to: "/",
        key: "Untitled34",
    },
    {
        title: "ATM출금",
        reward: "현금 인출 · 가까운 ATM",
        to: "/",
        key: "Untitled35",
    },
]